---
spring:
  application.name: chronos
  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB

server:
  port: 8080

management:
  endpoints.web:
    base-path: /management
    exposure.include: "*"

