---
spring:
  application.name: chronos
  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB
  main:
    banner-mode: off
  profiles.active: dev

server:
  port: 8080

management:
  endpoints.web:
    base-path: /management
    exposure.include: "*"

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    com.netflix: WARN
