# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2 # use CircleCI 2.0

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context:
            - docker-hub-credencials

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build Docs
      - run:
          name: Gradle build (Documents)
          command: gradle javadoc
      - store_artifacts:
          path: build/docs/

      # Run unit tests
      - run:
          name: Run unit tests
          command: gradle check
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/
